/* eslint-disable @typescript-eslint/no-require-imports */
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  await prisma.property.deleteMany();

  await prisma.property.createMany({
    data: [
      {
        title: "Lekki Phase 1 Detached Duplex",
        description: "Modern 5-bedroom duplex with ample parking and security estate access.",
        city: "Lagos",
        address: "Admiralty Way, Lekki Phase 1",
        ownerEmail: "agent.lagos@christoland.ng",
        kind: "HOUSE",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 420000000,
        bedrooms: 5,
        bathrooms: 5,
        areaSqft: 4650,
        imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        featured: true,
      },
      {
        title: "Guzape Hillside Terrace",
        description: "Premium terrace home with city view and fitted kitchen.",
        city: "Abuja",
        address: "Guzape District, FCT",
        ownerEmail: "sales.abuja@christoland.ng",
        kind: "HOUSE",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 265000000,
        bedrooms: 4,
        bathrooms: 4,
        areaSqft: 3320,
        imageUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156",
        featured: true,
      },
      {
        title: "Ikoyi Luxury Apartment",
        description: "Serviced apartment in a gated waterfront neighborhood.",
        city: "Lagos",
        address: "Bourdillon Road, Ikoyi",
        ownerEmail: "agent.lagos@christoland.ng",
        kind: "APARTMENT",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 310000000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqft: 2850,
        imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
        featured: true,
      },
      {
        title: "Apo Family Bungalow",
        description: "Affordable family bungalow in a calm, secured estate.",
        city: "Abuja",
        address: "Apo Resettlement, FCT",
        ownerEmail: "sales.abuja@christoland.ng",
        kind: "HOUSE",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 125000000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqft: 2140,
        imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
        featured: false,
      },
      {
        title: "GRA Corner Plot",
        description: "Prime residential land suitable for duplex development.",
        city: "Port Harcourt",
        address: "GRA Phase 2, Port Harcourt",
        ownerEmail: "southsouth@christoland.ng",
        kind: "LAND",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 85000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 5400,
        imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
        featured: false,
      },
      {
        title: "Bodija Redevelopment Plot",
        description: "Well-positioned plot for apartments or mixed-use development.",
        city: "Ibadan",
        address: "Bodija, Ibadan",
        ownerEmail: "southwest@christoland.ng",
        kind: "LAND",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 62000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 5000,
        imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
        featured: true,
      },
      {
        title: "Ibeju Lekki Dry Plot",
        description: "Verified dry plot close to proposed coastal highway corridor.",
        city: "Lagos",
        address: "Eleko Junction, Ibeju-Lekki",
        ownerEmail: "agent.lagos@christoland.ng",
        kind: "LAND",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 38000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 4800,
        imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
        featured: false,
      },
      {
        title: "Asokoro Smart Apartment",
        description: "Fully serviced apartment with gym and backup power.",
        city: "Abuja",
        address: "Yakubu Gowon Crescent, Asokoro",
        ownerEmail: "sales.abuja@christoland.ng",
        kind: "APARTMENT",
        listingTerm: "LEASE",
        status: "APPROVED",
        price: 28000000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqft: 1700,
        imageUrl: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0",
        featured: false,
      },
      {
        title: "Victoria Island Office Plot",
        description: "Commercial corner plot suitable for mixed-use development.",
        city: "Lagos",
        address: "Adeola Odeku, Victoria Island",
        ownerEmail: "agent.lagos@christoland.ng",
        kind: "LAND",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 550000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 6200,
        imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
        featured: true,
      },
      {
        title: "Enugu Lifestyle Bungalow",
        description: "Renovated family home in a quiet gated layout.",
        city: "Enugu",
        address: "Independence Layout, Enugu",
        ownerEmail: "east@christoland.ng",
        kind: "HOUSE",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 98000000,
        bedrooms: 4,
        bathrooms: 3,
        areaSqft: 2600,
        imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
        featured: false,
      },
      {
        title: "Ikeja Warehouse Yard",
        description: "Open land suitable for logistics base on 5-year lease.",
        city: "Lagos",
        address: "Alausa Axis, Ikeja",
        ownerEmail: "agent.lagos@christoland.ng",
        kind: "LAND",
        listingTerm: "LEASE",
        status: "APPROVED",
        price: 30000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 9800,
        imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
        featured: false,
      },
      {
        title: "Jabi Lakefront Plot Lease",
        description: "Strategic waterfront plot available on long lease terms.",
        city: "Abuja",
        address: "Jabi District, Abuja",
        ownerEmail: "sales.abuja@christoland.ng",
        kind: "LAND",
        listingTerm: "LEASE",
        status: "APPROVED",
        price: 45000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 7000,
        imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
        featured: false,
      },
      {
        title: "Trans Amadi Industrial Plot",
        description: "Industrial land for fabrication/storage on renewable lease.",
        city: "Port Harcourt",
        address: "Trans Amadi, Port Harcourt",
        ownerEmail: "southsouth@christoland.ng",
        kind: "LAND",
        listingTerm: "LEASE",
        status: "APPROVED",
        price: 26000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 8600,
        imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
        featured: false,
      },
      {
        title: "Sango Ota Development Land",
        description: "Affordable peri-urban land with excellent growth potential.",
        city: "Ogun",
        address: "Sango Ota, Ogun",
        ownerEmail: "southwest@christoland.ng",
        kind: "LAND",
        listingTerm: "SALE",
        status: "APPROVED",
        price: 22000000,
        bedrooms: 0,
        bathrooms: 0,
        areaSqft: 5200,
        imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
        featured: false,
      },
    ],
  });

  console.log("Seeded 14 Nigerian listings.");

  const finalCount = await prisma.property.count();
  console.log(`Total properties: ${finalCount}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
